"""added the image_url comlumn to the products table

Revision ID: 348c39df6119
Revises: 808f58177693
Create Date: 2024-04-17 13:25:32.624070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348c39df6119'
down_revision = '808f58177693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
